CREATE DATABASE IF NOT EXISTS `holocron_characters`;
USE `holocron_characters`;

CREATE TABLE IF NOT EXISTS `characters` (
  `guid` BIGINT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `level` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `gender` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `species` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `class_id` BIGINT UNSIGNED NOT NULL,
  `discipline_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `zone_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `pos_x` FLOAT NOT NULL DEFAULT 0,
  `pos_y` FLOAT NOT NULL DEFAULT 0,
  `pos_z` FLOAT NOT NULL DEFAULT 0,
  `orientation` FLOAT NOT NULL DEFAULT 0,
  `appearance_data` BLOB DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`guid`),
  KEY `idx_account` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
